# Generated by Django 4.2.20 on 2025-03-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='tbl_application',
        ),
        migrations.RenameModel(
            old_name='Bank',
            new_name='tbl_bank',
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='tbl_branch',
        ),
    ]
